cart/urls.py
from django.urls import path
from . import views 

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    
    
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path
from . import views 

app_name = 'orders'

urlpatterns = [
    path('', views.payment_method, name='payment_method'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment/', views.payment, name='payment'),
    path('payments/', views.payments, name='payments'),
    path('order_completed/', views.order_completed, name='order_complete'),
]

shop/urls.py
from django.urls import path
from django.utils.regex_helper import normalize
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('shop/<slug:category_slug>/', views.shop, name='categries'),
    path('shop/<slug:category_slug>/<slug:product_details_slug>/', views.product_details, name='product_details'),
    path('run_python_code/', views.run_python_code, name='run_python_code'),
    # path('run_python_code/<int:product_id>/', views.run_python_code, name='run_python_code'),
    path('search/', views.search, name='search'),
    path('review/<int:product_id>/', views.review, name='review'),
]

cart/models.py
from django.db import models

from shop.models import Product
from shop.models import Variation
from accounts.models import Account

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product
    

shop/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['review', 'rating']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from .models import Cart, CartItem
from shop.models import Product
from shop.models import Variation


def _cart_id(request):
    cart = request.session.session_key
    if not cart :
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id) # get the product
    product_variation = []
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST :
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass
        is_cart_item_exist = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exist:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variation.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0 :
                    item.variation.clear()
                    item.variation.add(*product_variation)
                item.save()

        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity = 1,
                user = current_user,
            )
            if len(product_variation) > 0 :
                cart_item.variation.clear()
                cart_item.variation.add(*product_variation)
            cart_item.save()

        return redirect('cart:cart')

    # if the user is not authencated
    else:        

        if request.method == 'POST':
            for item in request.POST :
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request)) # get the cart using the cart_id present in the session
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id=_cart_id(request))

        cart.save()

        is_cart_item_exist = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exist:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variation.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0 :
                    item.variation.clear()
                    item.variation.add(*product_variation)
                item.save()

        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity = 1,
                cart=cart,
            )
            if len(product_variation) > 0 :
                cart_item.variation.clear()
                cart_item.variation.add(*product_variation)
            cart_item.save()

        return redirect('cart:cart')

def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1 :
            cart_item.quantity -= 1
            cart_item.save()
        else :
            cart_item.delete()
    except:
        pass

    return redirect('cart:cart')


def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart:cart')

def cart(request, total_price=0, quantity=0, cart_items=None):
    grand_total = 0
    tax = 0

    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total_price += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
    
    except ObjectDoesNotExist:
        pass
    
    
    tax = round(((2 * total_price)/100), 2)
    grand_total = total_price + tax
    handing = 15.00
    total = float(grand_total) + handing

    context = {
        'total' : total_price,
        'quantity': quantity,
        'cart_items':cart_items,
        'order_total':total,
        'vat' : tax,
        'handing':handing,
    }

    return render(request, 'shop/cart/cart.html', context)

shop/views.py
from pathlib import Path

from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.conf import settings
from .models import Product, Category
from cart.views import _cart_id
from cart.models import CartItem
from .models import ReviewRating
from .forms import ReviewForm
from django.contrib import messages
from orders.models import OrderProduct
from .models import ProductGallery
from django.shortcuts import render
import cv2
import os
import cvzone
from cvzone.PoseModule import PoseDetector
from django.http import JsonResponse
def home(request):
    products = Product.objects.all().filter(is_available=True)
    
    context = {
        'products' : products,
    }
    return render(request, 'shop/index.html', context)


def shop(request, category_slug=None):
    categories = None
    products = None
    

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        products_count = products.count()
        
    else:
        products = Product.objects.all().filter(is_available=True)
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        products_count = products.count()
        
    
    for product in products:
        reviews = ReviewRating.objects.order_by('-updated_at').filter(product_id=product.id, status=True)

    context = {
        'category_slug': category_slug,
        'products' : paged_products,
        'products_count': products_count,
        
    }
    return render(request, 'shop/shop/shop.html', context)


def product_details(request, category_slug, product_details_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_details_slug)
        
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()
    except Exception as e:
        return e

    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(user=request.user, product_id=single_product.id).exists()
        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None

    reviews = ReviewRating.objects.order_by('-updated_at').filter(product_id=single_product.id, status=True)
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)

    context = {
        'single_product': single_product,
        'in_cart': in_cart,
        'orderproduct':orderproduct,
        'reviews': reviews,
        'product_gallery':product_gallery,
    }
    return render(request, 'shop/shop/product_details.html', context)


def search(request):
    products_count = 0
    products = None
    paged_products = None
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword :
            products = Product.objects.filter(Q(description__icontains=keyword) | Q(name__icontains=keyword))
            
            products_count = products.count()
            
    
    context = {
        'products': products,
        'products_count': products_count,
    }
    return render(request, 'shop/shop/search.html', context)



def review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id,product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you, your review updated!')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Thank you, your review Posted!')
                return redirect(url)


def run_python_code(request):
    product_name = request.GET.get('name','')
    shirt_path = os.path.join(settings.BASE_DIR, f'media/photos/products/{product_name}.png')

    cap = cv2.VideoCapture(0)
    detector = PoseDetector(staticMode=False,
                            modelComplexity=1,
                            smoothLandmarks=False,
                            enableSegmentation=False,
                            smoothSegmentation=True,
                            detectionCon=0.5,
                            trackCon=0.5)

    # Path to the shirt image

    imgshirt = cv2.imread(shirt_path, cv2.IMREAD_UNCHANGED)

    fixedratio = 262 / 190  # width of shirt / width of points
    shirt_ratio_width_height = 581 / 440


    # Define the face landmark indices to ignore
    face_landmark_indices = list(range(0, 17))

    while True:
        success, img = cap.read()

        # Detect pose
        img = detector.findPose(img, draw=False)

        # Find the landmarks, bounding box, and center of the body in the frame
        # Set draw=True to draw the landmarks and bounding box on the image
        lmList, bboxInfo = detector.findPosition(img, draw=False, bboxWithHands=False)

        # Check if any body landmarks are detected
        if lmList:
            lm11 = lmList[11][0:2]
            lm12 = lmList[12][0:2]

            width_of_shirt = int((lm11[0] - lm12[0]) * fixedratio)
            imgshirt_resized = cv2.resize(imgshirt, (width_of_shirt, int(width_of_shirt * shirt_ratio_width_height)))
            currentscale = (lm11[0] - lm12[0]) / 190
            offset = int(44 * currentscale), int(48 * currentscale)

            try:
                img = cvzone.overlayPNG(img, imgshirt_resized, (lm12[0] - offset[0], lm12[1] - offset[1]))
            except:
                pass

        cv2.imshow("Image", img)

        if cv2.waitKey(1) == 27:
            cv2.destroyAllWindows()
            cap.release()
            break
    return render(request, 'index.html')

templates/shop/cart/cart.html
{% extends '../../base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block content %}
<div  class="pages-title section-padding">
			<div  class="container">
				<div  style="background:#40394a" class="row">
					<div class="col-xs-12">
						<div class="pages-title-text text-center">
							<h2 style="color:#f4cca4">Cart</h2>
							<ul class="text-left">
								<li><a style="color:#d99879" href="\">Home </a></li>
								<li style="color:#d99879"><span> // </span>Cart</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- pages-title-end -->
		<!-- cart content section start -->
		{% if not cart_items %}
		<div style="font-size:18px; margin-bottom:300px;margin-top:30px" class="container alert alert-info text-center" role="alert">
		<b>Your Cart Is Empty,&nbsp;&nbsp; <a href="{% url 'shop:shop' %}" style="color:#21094e;text-decoration: underline;">Go To Shop<a></b>
		</div>
		
		{% else %}
		<section style="background:#1c1427" class="pages cart-page section-padding">
			<div class="container">
				<div class="row">
					<div class="col-xs-12">
						<div style="border-radius:20px;" class="table-responsive padding60">
							<table class="wishlist-table text-center">
								<thead>
									<tr>
										<th style="border-radius:20px 0 0 20px;">Image</th>
										<th>Name</th>
										<th>Price</th>
										<th>quantity</th>
										<th>Total Price</th>
										<th style="border-radius:0 20px 20px 0;">Remove</th>
									</tr>
								</thead>
								<tbody>
                                    {% for cart_item in cart_items %}
									<tr>
										<td class="td-img text-center">
											<a href="{{cart_item.product.get_prodcut_details_url}}"><img style="border-radius:10px;" width="100" height="100" src="{{cart_item.product.image.url}}" alt="Add Product" /></a>
											
										</td>
										<td>
										<div class="items-dsc">
											<h5><a href="{{cart_item.product.get_prodcut_details_url}}">{{cart_item.product.name}}</a></h5>

											{% if cart_item.variation.all %}
												{% for item in cart_item.variation.all %}
												<p>{{item.variation_category | capfirst}} : {{item.variation_value | capfirst}}</p>
												{% endfor %}
											{% endif %}
											
										</div>
										</td>
										<td>${{cart_item.product.price}}</td>
										<td>
										<div class="plus-minus" >
										<form style="" action="{% url 'cart:add_cart' cart_item.product.id %}" method="POST">
											<a style="background:#232323;color:#fff;height:35px;margin-top:-5px;width:40px; border-radius: 4px;" href="{% url 'cart:remove_cart' cart_item.product.id cart_item.id %}" ><i class="fa fa-minus"></i></a>
											<input style=" height:35px"  class="form-control" value="{{cart_item.quantity}}" readonly>
											<!-- <a style="background:#232323;color:#fff" href="{% url 'cart:add_cart' cart_item.product.id %}" >+</a> -->
											<!--
											<form action="{% url 'cart:add_cart' cart_item.product.id %}" method="POST">
												{% csrf_token %}
												{% for item in cart_item.variation.all %}
												<input type="hidden" name={{ item.variation_category | capfirst }} value={{ item.variation_value |capfirst }}>
												{% endfor %}
												<button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
											</form>
											-->
											{% csrf_token %}
											{% for item in cart_item.variation.all %}
											<input type="hidden" name={{ item.variation_category | capfirst }} value={{ item.variation_value |capfirst }}>
											{% endfor %}
											<button style="background:#232323;color:#fff; height:35px; margin-top:-3px " class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
											</form>
										</div>
										</td>
										<td >
											<strong style="color:#f4cca4">${{cart_item.sub_total}}</strong>
										</td>
										<td ><a href="{% url 'cart:remove_cart_item' cart_item.product.id cart_item.id %}" ><i style="background:#ba135d;color:#f4cca4" onclick="return confirm('Are you really want delete this?')" class="mdi mdi-close"></i></a></td>
									</tr>
									{% endfor %}
									<tr>
									</tr>
								</tbody>
							</table><br><br><br>
							<div class="cart-form-text pay-details table-responsive">
								<table>
									<tbody style="color:#f4cca4">
										<tr>
											<th style="font-size:18px">Cart Subtotal</th>
											<td style="font-size:18px">${{total}}</td>
										</tr>
										<tr>
											<th style="font-size:18px">Shipping and Handing</th>
											<td style="font-size:18px">${{handing}}</td>
										</tr>
										<tr>
											<th style="font-size:18px">Vat</th>
											<td style="font-size:18px">${{vat}}</td>
										</tr>
									</tbody>
									<tfoot>
										<tr>
											<th style="color:#d99879; font-size:22px" class="tfoot-padd">Order total</th>
											<td style="color:#d99879; font-size:22px" class="tfoot-padd">${{order_total}}</td>
										</tr>
									</tfoot>
								</table>
								<br><br><br>
								<div  class="list-btn text-center">
									<a href="{% url 'orders:checkout' %}" class="btn" style="background:#f4cca4;color:#1c1427; text-transform:capitalize; font-size:18px; width:60%"><b>Checkout</b></a><br><br>
									<a href="{% url 'shop:shop' %}" class="btn btn-warning"    style=" background:none;color:#f4cca4; text-transform:capitalize; font-size:18px; width:60%">continue shopping</a>
								</div>
							</div>
						</div>
					</div>
				</div>
                <br>

			</div>
		</section>
		{% endif %}
{% endblock content %}