accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),

    path('', views.dashboard, name='dashboardd'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    
    path('forget_password/', views.forget_password, name="forget_password"),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('reset_password/', views.reset_password, name="reset_password"),
]

cart/urls.py
from django.urls import path
from . import views 

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    
    
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class AccountManger(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email :
            raise ValueError('User must have an email address')
        if not username :
            raise ValueError('User must have an username')

        user = self.model(
            # normalize_email => if as write captel char it turn for samll char
            email = self.normalize_email(email),
            first_name = first_name,
            last_name = last_name,
            username = username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, first_name, last_name, username, email, password):
        user = self.create_user(
            email = self.normalize_email(email),
            first_name = first_name,
            last_name = last_name,
            username = username,
            password = password,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        
        user.save(using=self._db)
        return user

class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    Phone_number = models.CharField(max_length=50)

    # Required
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)
    
    
    date_joined_for_format = models.DateTimeField(auto_now_add=True)
    last_login_for_format  = models.DateTimeField(auto_now_add=True)
    def date_joined(self):
        return self.date_joined_for_format.strftime('%B %d %Y')
    def last_login(self):
        return self.last_login_for_format.strftime('%B %d %Y')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = AccountManger()

    def __str__(self):
        return self.email
    
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    # he has all the permission to do all the changes
    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True


class UserProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    address = models.TextField(blank=True, max_length=500)
    profile_picture = models.ImageField(blank=True, upload_to='userprofile',default='static/user_image_default.png')
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)

    def __str__(self):
        return self.user.first_name

accounts/forms.py
from django import forms
from .models import Account ,UserProfile

class RegisterationFrom(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        # 'placeholder' : 'Enter Password',
        'class' : 'form-control',
    }))
    repeat_password = forms.CharField(widget=forms.PasswordInput(attrs={
        # 'placeholder' : 'Repeate Password',
        'class' : 'form-control',
    }))
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'Phone_number', 'email', 'password']

    def __init__(self, *args, **kwargs):
        super(RegisterationFrom, self).__init__(*args, **kwargs)
        # self.fields['first_name'].widget.attrs['placeholder'] = 'First name'
        # self.fields['last_name'].widget.attrs['placeholder'] = 'Last name'
        # self.fields['email'].widget.attrs['placeholder'] = 'Email'
        # self.fields['Phone_number'].widget.attrs['placeholder'] = 'Phone Number'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'input100'

    
    def clean(self):
        cleaned_data = super(RegisterationFrom, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('repeat_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match!"
            )
        
      

class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'Phone_number')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages = {'invalid':("Image files only")}, widget=forms.FileInput)
    class Meta:
        model = UserProfile
        fields = ('address', 'city', 'state', 'country', 'profile_picture')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

accounts/views.py
import requests

from django.shortcuts import render, redirect,get_object_or_404
from django.contrib import messages, auth   
from django.contrib.auth.decorators import login_required

from .forms import RegisterationFrom, UserForm, UserProfileForm
from .models import Account

# verification email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.utils.encoding import force_str
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from .token import account_activation_token
from django.conf import settings

import uuid

from cart.views import _cart_id
from cart.models import Cart, CartItem
from orders.models import Order
from .models import UserProfile
from orders.models import OrderProduct

def register(request):
    if request.method == "POST":
        form = RegisterationFrom(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['Phone_number']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = email.split("@")[0]
            user = Account.objects.create_user(first_name=first_name, last_name=last_name, email=email, username=username, password=password)
            user.Phone_number = phone_number
            # user.is_active = True
            user.save()
            
            
            # Create a user profile
            profile = UserProfile()
            profile.user_id = user.id
            # profile.profile_picture = 'default/default-user.png'
            profile.save()

            # USER ACTIVATION
            current_site = get_current_site(request)
            subject = 'Please activate your account'
            message = render_to_string('shop/accounts/email_activate/account_verification_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(subject, message, to=[to_email])
            send_email.send()
    
            # messages.success(request, 'Check Gmail To Active Your Account')
            return redirect('/account/register/?command=verification&email='+email)

            
            # auth.login(request, user)
            # messages.success(request, 'You Loged in')
            # return redirect('accounts:dashboard')


    else : # request == GET
        form = RegisterationFrom()

    context = {
        'forms': form,
    }

    return render(request, 'shop/accounts/register.html', context)

def login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password)

        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)

                    # Getting the product variations by cart id 
                    product_variation = []
                    for item in cart_item:
                        variation = item.variation.all()
                        product_variation.append(list(variation))

                    # Get the cart items from the user to access his product variations
                    cart_item = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        existing_variation = item.variation.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)

                    for pr in product_variation:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            cart_item = CartItem.objects.filter(cart=cart)

                            for item in cart_item:
                                item.user = user
                                item.save()
            except:
                pass

            auth.login(request, user)
            url = request.META.get('HTTP_REFERER')
            try:
                query = requests.utils.urlparse(url).query
                # next=/cart/checkout/
                params = dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(nextPage)
            except:
                return redirect('accounts:dashboard')
            return redirect('accounts:dashboard')
        else:
            messages.error(request, 'Your email or password is wrong!')
            return redirect('accounts:login')
    return render(request, 'shop/accounts/login.html')


@login_required(login_url = 'accounts:login')
def logout(request):
    auth.logout(request)
    messages.success(request, "You've successfully logged out . Come back soon!")
    return redirect('accounts:login')


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Your account is activated, log in and let's go.")
        return redirect('accounts:login')
    else:
        messages.error(request, "Invalid activation link, Try again!")
        return redirect('accounts:register')

@login_required(login_url = 'accounts:login')
def dashboard(request):
    orders = Order.objects.order_by('-created_at').filter(user_id=request.user.id, is_ordered=True)
    profile = UserProfile.objects.get(user_id=request.user.id)
    
    orders_count = orders.count()
    context = {
        'orders_count':orders_count,
        'profile':profile,
        
    }
    return render(request, 'shop/accounts/dashboard/dashboard.html', context)



@login_required(login_url = 'accounts:login')
def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
    orders_count = orders.count()
    
    context = {
        'orders':orders,
        'orders_count':orders_count,
    }
    return render(request, 'shop/accounts/dashboard/my_orders.html', context)


@login_required(login_url = 'accounts:login')
def edit_profile(request):
    userprofile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile has been updated.')
            return redirect('accounts:edit_profile')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=userprofile)
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'userprofile': userprofile,
    }
    return render(request, 'shop/accounts/dashboard/edit_profile.html', context)


@login_required(login_url = 'accounts:login')
def change_password(request):
    if request.method == 'POST':
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']
        repeat_new_password = request.POST['repeat_new_password']

        user = Account.objects.get(username__exact=request.user.username)

        if new_password == repeat_new_password:
            success = user.check_password(old_password)
            if success :
                user.set_password(new_password)
                user.save()
                auth.login(request, user)
                messages.success(request, 'Password Updated successfully.')
                return redirect('accounts:change_password')
            else:
                messages.error(request, 'Old password is wrong')
                return redirect('accounts:change_password')
        else:
            messages.error(request, 'Password does not match')
            return redirect('accounts:change_password')
    return render(request, 'shop/accounts/dashboard/change_password.html')


@login_required(login_url = 'accounts:login')
def order_detail(request,order_id):
    order_detail = OrderProduct.objects.filter(order__order_number=order_id)
    order = Order.objects.get(order_number=order_id)

    subtotal = 0
    for x in order_detail:
        subtotal += x.product_price * x.quantity

    context = {
        'order_detail': order_detail,
        'order': order,
        'subtotal': subtotal,
    }
    return render(request, 'shop/accounts/dashboard/order_detail.html', context)


def forget_password(request):
    if request.method == 'POST':
        email = request.POST['email']
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)
            

templates/shop/accounts/dashboard/change_password.html
{% extends '../../../base.html' %}
{% load static %}
{% block title %}Change Password{% endblock title %}
{% block content %}

<div  class="pages-title section-padding">
    <div  class="container">
        <div  style="background:#40394a" class="row">
            <div class="col-xs-12">
                <div class="pages-title-text text-center">
                    <h2 style="color:#f4cca4">Change Password</h2>
                    <ul class="text-left">
                        <li><a style="color:#d99879" href="\">Home </a></li>
                        <li style="color:#d99879"><span> // </span>Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<section style="background:#1C1427" class="section-conten padding-y bg">
    <br><br>
    <span style="font-size:18px"><b> {% include "includes/alerts.html" %} </b></span>
  <div class="container">
	<div class="row">
    {% include "includes/dashboard_slider.html" %}
	<main style="background:#40394A;border-radius:10px" class="col-md-9"><br>
    <form action="{% url 'accounts:change_password' %}" method="POST" enctype="multipart/form-data">
		<article class="card">
		<header class="card-header text-center">
            <strong style="font-size:20px;float:left" class="d-inline-block mr-3">Change Password</strong>
            <input style="float:right;width:20%;color:#1C1427;font-size:18px;font-weight: bold;" type="submit" value="Change" class="btn btn-warning">
        </header>
		<div class="card-body"><br><br><br>
			<div class="row">
			<div class="col-md-12">
					{% csrf_token %}
					<div class="form-group col-md-12">
						<label>Old Password</label>
						<input type="password" name="old_password" class="form-control" required>
					</div>
					<div class="form-group col-md-12">
						<label>New Password</label>
						<input type="password" name="new_password"  class="form-control" required>
					</div>
					<div class="form-group col-md-12">
						<label>Repeat New Password</label>
						<input type="password" name="repeat_new_password"  class="form-control" required>
					</div>
			</div>
			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
        </form>
	</main>
</div> <!-- row.// -->
</div>

<br>
</section>


<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

templates/shop/accounts/dashboard/dashboard.html
{% extends '../../../base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock title %}
{% block content %}

<div  class="pages-title section-padding">
    <div  class="container">
        <div  style="background:#40394a" class="row">
            <div class="col-xs-12">
                <div class="pages-title-text text-center">
                    <h2 style="color:#f4cca4">dashboard</h2>
                    <ul class="text-left">
                        <li><a style="color:#d99879" href="\">Home </a></li>
                        <li style="color:#d99879"><span> // </span>Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<section style="background:#1c1427" class="section-conten padding-y bg">
    <br><br>
    <div class="container">
        <div class="row">
            <span class="font-size:18px"><b> {% include "includes/alerts.html" %} </b></span>
            {% include "includes/dashboard_slider.html" %}
        
            <main style="background:#40394A; border-radius:10px" class="col-md-9">
                <article class="card">
                <br>
                <header class="card-header text-center">
                    <span style="font-size:20px" class="d-inline-block">Logged in as :</span>
                    <strong style="font-size:20px">{{user.full_name | title}}</strong>
                </header>
                <hr>
                <div class="card-body">
                    <div  class="row">
                        <div style="" class="col-md-6">
                            <div  class="card" style="text-align:center; background:#1C1427;border-radius:7px;margin-bottom:10px">
                            
                                <div style="font-size:18px;padding:10px" class="card-body">
                                    <img src="{{profile.profile_picture.url}}" alt="Profile Picture" width="100" style="border-radius:50px;">
                                    <br>
                                    <br>
                                    <p style="font-size:16px;" class="mb-0"><span style="float:left"><b>User Name :</b></span> <span style="float:right">{{user.username}}</span></p><br><hr>
                                    <p style="font-size:16px;" class="mb-0"><span style="float:left"><b>Email :</b></span> <span style="float:right">{{user.email}}</span></p><br><hr>
                                    <p style="font-size:16px;" class="mb-0"><span style="float:left"><b>Phone Number :</b></span> <span style="float:right">{{user.Phone_number}}</span></p><br><hr>
                                    
                                    {% if profile.address %}
                                    <p style="font-size:16px;" class="mb-0"><span style="float:left"><b>Address :</b></span> <span style="float:right">{{profile.address}}</span></p><br><hr>
                                    {% endif %}
                                    
                                    {% if profile.city %}
                                    <p style="font-size:16px;" class="mb-0"><span style="float:left"><b>City :</b></span> <span style="float:right">{{profile.city}}</span></p><br><hr>
                                    {% endif %}
                                    
                                    {% if profile.state %}
                                    <p style="font-size:16px;" class="mb-0"><span style="float:left"><b>State :</b></span> <span style="float:right">{{profile.state}}</span></p><br><hr>
                                    {% endif %}

                                    {% if profile.country %}
                                    <p style="font-size:16px;" class="mb-0"><span style="float:left"><b>Country :</b></span> <span style="float:right">{{profile.country}}</span></p><br><hr>
                                    {% endif %}
                                    
                                </div>
                            </div>
                        </div>
                        <div  class="col-md-6">
                            <div  class="card" style="text-align:center;">
                                <div style="background:#1C1427;border-radius:7px;padding:10px;height:150px" style="font-size:18px" class="card-body">
                                    <h5 style="margin-top:30px;font-size:23px" class="card-title">Total Orders</h5>
                                    <h4 style="font-size:25px">{{orders_count}}</h4>
                                    
                                </div>
                            </div>
                        </div><br>
                    </div>
                </div>
                </article>
            </main>
        </div>
    </div><br>
</section>


<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

templates/shop/accounts/dashboard/edit_profile.html
{% extends '../../../base.html' %}
{% load static %}
{% block title %}Edit Profile{% endblock title %}
{% block content %}

<div  class="pages-title section-padding">
    <div  class="container">
        <div  style="background:#40394a" class="row">
            <div class="col-xs-12">
                <div class="pages-title-text text-center">
                    <h2 style="color:#f4cca4">Edit Profile</h2>
                    <ul class="text-left">
                        <li><a style="color:#d99879" href="\">Home </a></li>
                        <li style="color:#d99879"><span> // </span>Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<section style="background:#1C1427" class="section-conten padding-y bg">
    <br><br>
  
<span style="font-size:16px"><b> {% include "includes/alerts.html" %} </b></span>
<div class="container">
	<div class="row">
    {% include "includes/dashboard_slider.html" %}
	<main class="col-md-9">
    <form style="background:#40394A; padding:20px;border-radius:10px" action="{% url 'accounts:edit_profile' %}" method="POST" enctype="multipart/form-data">
		<article class="card">
		<header class="card-header text-center">
            <strong style="font-size:20px;float:left" class="d-inline-block mr-3">Edit your profile</strong>
            <input style="float:right;width:20%;color:#1C1427;font-size:18px;font-weight: bold;" type="submit" value="Edit" class="btn btn-warning">
        </header>
		<div class="card-body">
			
            <div class="text-center">
				<img src="{{userprofile.profile_picture.url}}" alt="Profile Picture" width="100" style="border-radius:50px;">
			</div>
            <br>
			<div class="row">
			<div class="col-md-12">
				
					{% csrf_token %}
					<div class="form-row">
						<div class="form-group col-md-6">
							<label>First Name</label>
							{{user_form.first_name}}
						</div>
						<div class="form-group col-md-6">
							<label>Last Name</label>
							{{user_form.last_name}}
						</div>
					</div>
					<div class="form-row">
						<div class="form-group col-md-6">
							<label>Phone Number</label>
							{{user_form.Phone_number}}
						</div>
						<div class="form-group col-md-6">
							<label>Profile Picture</label>
							{{profile_form.profile_picture}}
						</div>
					</div>
					<div style="margin-bottom:10px" class="col-md-12">
						<label>Address</label>
						{{profile_form.address}}
					</div><br>
					<div class="form-row">
						<div class="form-group col-md-4">
							<label>City</label>
							{{profile_form.city}}
						</div>
						<div class="form-group col-md-4">
							<label>State</label>
							{{profile_form.state}}
						</div>
						<div class="form-group col-md-4">
							<label>Country</label>
							{{profile_form.country}}
						</div>
					</div>
					
				
			</div>

			</div> <!-- row.// -->
		</div> <!-- card-body .// -->

		</article> <!-- order-group.// -->
        </form>
	</main>
</div> <!-- row.// -->
</div>


<br>
</section>


<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}

templates/shop/accounts/dashboard/my_orders.html
{% extends '../../../base.html' %}
{% load static %}
{% block title %}My Orders{% endblock title %}
{% block content %}

<div  class="pages-title section-padding">
    <div  class="container">
        <div  style="background:#40394a" class="row">
            <div class="col-xs-12">
                <div class="pages-title-text text-center">
                    <h2 style="color:#f4cca4">My Orders</h2>
                    <ul class="text-left">
                        <li><a style="color:#d99879" href="\">Home </a></li>
                        <li style="color:#d99879"><span> // </span>Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<section style="background:#1C1427" class="section-conten padding-y bg">
    <br><br>
    <span style="font-size:25px"><b> {% include "includes/alerts.html" %} </b></span>
  <div class="container">
    
    <div class="row">
      {% include "includes/dashboard_slider.html" %}

      <main style="background:#40394A;border-radius:10px" class="col-md-9">
        <article class="card"><br>
          <header class="card-header text-center">
            <strong style="font-size:25px" class="d-inline-block mr-3">Total Orders : {{orders_count}}</strong>
          </header>
          <br>
          {% if orders_count >= 1 %}
          <table class="table table-hover text-center">
            <thead >
              <tr >
                <th style="background:#D99879;color:#1C1427;font-size:16px;border-radius:10px 0  0 0 ; " scope="col">Order Number</th>
                <th style="background:#D99879;color:#1C1427;font-size:16px" scope="col">Total Price</th>
                <th style="background:#D99879;color:#1C1427;font-size:16px" scope="col">Date</th>
                <th style="background:#D99879;color:#1C1427;font-size:16px; border-radius:0 10px 0 0 " scope="col"></th>
              </tr>
              </tr>
            </thead>
            <tbody>
              {% for order in orders %}
              <tr class='hav'>
                <th style="background:#1C1427;font-size:16px" class="text-center" scope="row">{{order.order_number}}</th>
                <td style="background:#1C1427;font-size:16px" >${{order.order_total}}</td>
                <td style="background:#1C1427;font-size:16px" >{{order.order_created}}</td>
                <td style="background:#1C1427;font-size:16px"><b><a class="btn" style="background:#F4CCA4; color:#000" href='{% url "accounts:order_detail" order.order_number%}'><b>View Details</b></a></b></td>
              </tr>
              
              {% endfor %}

            </tbody>

          </table>
          <br>
          <div>
          {% endif %}
        </article> <!-- order-group.// -->
      </main>
      <br>
    </div> <!-- row.// -->
  </div>

</div>

<br>
</section>


<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock content %}