accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),

    path('', views.dashboard, name='dashboardd'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    
    path('forget_password/', views.forget_password, name="forget_password"),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('reset_password/', views.reset_password, name="reset_password"),
]

cart/urls.py
from django.urls import path
from . import views 

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    
    
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from django.utils.regex_helper import normalize
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('shop/<slug:category_slug>/', views.shop, name='categries'),
    path('shop/<slug:category_slug>/<slug:product_details_slug>/', views.product_details, name='product_details'),
    path('run_python_code/', views.run_python_code, name='run_python_code'),
    # path('run_python_code/<int:product_id>/', views.run_python_code, name='run_python_code'),
    path('search/', views.search, name='search'),
    path('review/<int:product_id>/', views.review, name='review'),
]

accounts/forms.py
from django import forms
from .models import Account ,UserProfile

class RegisterationFrom(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        # 'placeholder' : 'Enter Password',
        'class' : 'form-control',
    }))
    repeat_password = forms.CharField(widget=forms.PasswordInput(attrs={
        # 'placeholder' : 'Repeate Password',
        'class' : 'form-control',
    }))
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'Phone_number', 'email', 'password']

    def __init__(self, *args, **kwargs):
        super(RegisterationFrom, self).__init__(*args, **kwargs)
        # self.fields['first_name'].widget.attrs['placeholder'] = 'First name'
        # self.fields['last_name'].widget.attrs['placeholder'] = 'Last name'
        # self.fields['email'].widget.attrs['placeholder'] = 'Email'
        # self.fields['Phone_number'].widget.attrs['placeholder'] = 'Phone Number'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'input100'

    
    def clean(self):
        cleaned_data = super(RegisterationFrom, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('repeat_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match!"
            )
        
      

class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'Phone_number')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages = {'invalid':("Image files only")}, widget=forms.FileInput)
    class Meta:
        model = UserProfile
        fields = ('address', 'city', 'state', 'country', 'profile_picture')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

accounts/views.py
import requests

from django.shortcuts import render, redirect,get_object_or_404
from django.contrib import messages, auth   
from django.contrib.auth.decorators import login_required

from .forms import RegisterationFrom, UserForm, UserProfileForm
from .models import Account

# verification email
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.utils.encoding import force_str
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from .token import account_activation_token
from django.conf import settings

import uuid

from cart.views import _cart_id
from cart.models import Cart, CartItem
from orders.models import Order
from .models import UserProfile
from orders.models import OrderProduct

def register(request):
    if request.method == "POST":
        form = RegisterationFrom(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['Phone_number']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = email.split("@")[0]
            user = Account.objects.create_user(first_name=first_name, last_name=last_name, email=email, username=username, password=password)
            user.Phone_number = phone_number
            # user.is_active = True
            user.save()
            
            
            # Create a user profile
            profile = UserProfile()
            profile.user_id = user.id
            # profile.profile_picture = 'default/default-user.png'
            profile.save()

            # USER ACTIVATION
            current_site = get_current_site(request)
            subject = 'Please activate your account'
            message = render_to_string('shop/accounts/email_activate/account_verification_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(subject, message, to=[to_email])
            send_email.send()
    
            # messages.success(request, 'Check Gmail To Active Your Account')
            return redirect('/account/register/?command=verification&email='+email)

            
            # auth.login(request, user)
            # messages.success(request, 'You Loged in')
            # return redirect('accounts:dashboard')


    else : # request == GET
        form = RegisterationFrom()

    context = {
        'forms': form,
    }

    return render(request, 'shop/accounts/register.html', context)

def login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password)

        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)

                    # Getting the product variations by cart id 
                    product_variation = []
                    for item in cart_item:
                        variation = item.variation.all()
                        product_variation.append(list(variation))

                    # Get the cart items from the user to access his product variations
                    cart_item = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        existing_variation = item.variation.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)

                    for pr in product_variation:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            cart_item = CartItem.objects.filter(cart=cart)

                            for item in cart_item:
                                item.user = user
                                item.save()
            except:
                pass

            auth.login(request, user)
            url = request.META.get('HTTP_REFERER')
            try:
                query = requests.utils.urlparse(url).query
                # next=/cart/checkout/
                params = dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(nextPage)
            except:
                return redirect('accounts:dashboard')
            return redirect('accounts:dashboard')
        else:
            messages.error(request, 'Your email or password is wrong!')
            return redirect('accounts:login')
    return render(request, 'shop/accounts/login.html')


@login_required(login_url = 'accounts:login')
def logout(request):
    auth.logout(request)
    messages.success(request, "You've successfully logged out . Come back soon!")
    return redirect('accounts:login')


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Your account is activated, log in and let's go.")
        return redirect('accounts:login')
    else:
        messages.error(request, "Invalid activation link, Try again!")
        return redirect('accounts:register')

@login_required(login_url = 'accounts:login')
def dashboard(request):
    orders = Order.objects.order_by('-created_at').filter(user_id=request.user.id, is_ordered=True)
    profile = UserProfile.objects.get(user_id=request.user.id)
    
    orders_count = orders.count()
    context = {
        'orders_count':orders_count,
        'profile':profile,
        
    }
    return render(request, 'shop/accounts/dashboard/dashboard.html', context)



@login_required(login_url = 'accounts:login')
def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
    orders_count = orders.count()
    
    context = {
        'orders':orders,
        'orders_count':orders_count,
    }
    return render(request, 'shop/accounts/dashboard/my_orders.html', context)


@login_required(login_url = 'accounts:login')
def edit_profile(request):
    userprofile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile has been updated.')
            return redirect('accounts:edit_profile')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=userprofile)
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'userprofile': userprofile,
    }
    return render(request, 'shop/accounts/dashboard/edit_profile.html', context)


@login_required(login_url = 'accounts:login')
def change_password(request):
    if request.method == 'POST':
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']
        repeat_new_password = request.POST['repeat_new_password']

        user = Account.objects.get(username__exact=request.user.username)

        if new_password == repeat_new_password:
            success = user.check_password(old_password)
            if success :
                user.set_password(new_password)
                user.save()
                auth.login(request, user)
                messages.success(request, 'Password Updated successfully.')
                return redirect('accounts:change_password')
            else:
                messages.error(request, 'Old password is wrong')
                return redirect('accounts:change_password')
        else:
            messages.error(request, 'Password does not match')
            return redirect('accounts:change_password')
    return render(request, 'shop/accounts/dashboard/change_password.html')


@login_required(login_url = 'accounts:login')
def order_detail(request,order_id):
    order_detail = OrderProduct.objects.filter(order__order_number=order_id)
    order = Order.objects.get(order_number=order_id)

    subtotal = 0
    for x in order_detail:
        subtotal += x.product_price * x.quantity

    context = {
        'order_detail': order_detail,
        'order': order,
        'subtotal': subtotal,
    }
    return render(request, 'shop/accounts/dashboard/order_detail.html', context)


def forget_password(request):
    if request.method == 'POST':
        email = request.POST['email']
        if Account.objects.filter(email=email).exists():
            user = Account.objects.get(email__exact=email)
            

templates/shop/accounts/forget_password/forget_password.html
{% load static %}
<html lang="en">
<head>
	<title>Reset Password</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'log/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'log/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'log/fonts/iconic/css/material-design-iconic-font.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'log/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->	
    <link rel="stylesheet" type="text/css" href="{% static 'log/vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'log/vendor/animsition/css/animsition.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'log/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->	
    <link rel="stylesheet" type="text/css" href="{% static 'log/vendor/daterangepicker/daterangepicker.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'log/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'log/css/main.css' %}">
    
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

</head>
<body >
	<div  class="limiter">
		<div  style="background:#40394a" class="container-login100">
				{% if request.GET.command == 'resetpassword' %}
				<div style="width:70%;background:#1c1427" class="alert alert-warning text-center" role="alert">
				<br>
				<b><p style="font-size:25;color:#f4cca4">We sent message to your email, check your email to reset password</p></b><br><br><br>
				<a class="btn btn-warning "  style="font-size:20px; background:#f4cca4;color:#1c1427;width:250px;" href="{% url 'shop:home' %}">Back to home</a><br><br>
				
				</div>
				{% else %}
			<div style="width:39%;background:#1c1427" class="wrap-login100">
				<form class="login100-form validate-form" action="{% url 'accounts:forget_password' %}" method="POST">
					{% csrf_token %}
					<span style="color:#f4cca4;font-weight: 800;"  class="login100-form-title p-b-48">
						<span style="color:#d99879">E -</span> S H O P
					</span>
					<span style="color:#f4cca4" class="login100-form-title p-b-26">
						Reset Password
					</span>
					{% include "includes/alerts.html" %}
					<br>
					<div class="wrap-input100 validate-input">
						<input class="input100" type="text" name="email">
						<span class="focus-input100" data-placeholder="Email"></span>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button type="submit" class="login100-form-btn">
								Send Email
							</button>
						</div>
					</div>
                    <br><br><br>
                    <a style="font-size:17px; color:#d99879" class="txt2" href="{% url 'accounts:login' %}">
                        Login
                    </a>
                    <br><br><hr>
                    <a href="{% url 'shop:home' %}" style="background:#f4cca4;color:#1c1427 " class="btn btn-warning"><i class="fas fa-angle-double-left"></i>&nbsp;&nbsp;  Back to Home</a>
				</form>
				{% endif %}
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
	
<!--===============================================================================================-->
<script src="{% static 'log/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'log/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'log/vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'log/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'log/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'log/vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'log/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'log/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'log/js/main.js' %}"></script>
</body>
</html>

templates/shop/accounts/forget_password/reset_password.html
{% load static %}
<html lang="en">
<head>
	<title>Reset Password</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'log/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'log/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'log/fonts/iconic/css/material-design-iconic-font.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'log/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->	
    <link rel="stylesheet" type="text/css" href="{% static 'log/vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'log/vendor/animsition/css/animsition.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'log/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->	
    <link rel="stylesheet" type="text/css" href="{% static 'log/vendor/daterangepicker/daterangepicker.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'log/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'log/css/main.css' %}">
    
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

</head>
<body >
	<div  class="limiter">
		<div  style="background:#40394a" class="container-login100">
			<div style="width:39%;background:#1c1427" class="wrap-login100">
				<form class="login100-form validate-form" action="{% url 'accounts:reset_password' %}" method="POST">
					{% csrf_token %}
					<span style="color:#f4cca4;font-weight: 800;"  class="login100-form-title p-b-48">
						<span style="color:#d99879">E -</span> S H O P
					</span>
					<span style="color:#f4cca4" class="login100-form-title p-b-26">
						Reset Password
					</span>
					{% include "includes/alerts.html" %}<br>
					<div class="wrap-input100 validate-input">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="password" name="password">
						<!--{{forms.password}}-->
						<span class="focus-input100" data-placeholder="Password"></span>
					</div>
					<div class="wrap-input100 validate-input">
						<input class="input100" type="password" name="confirm_password">
						<!--{{ forms.repeat_password }}-->
						<span class="focus-input100" data-placeholder="Confirm Password"></span>
					</div>
                    
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button type="submit" class="login100-form-btn">
								Reset Password
							</button>
						</div>
					</div>
                    <br><br>
                    <hr><br>
                    <a href="{% url 'shop:home' %}" style="background:#f4cca4;color:#1c1427 " class="btn btn-warning"><i class="fas fa-angle-double-left"></i>&nbsp;&nbsp;  Back to Home</a>
                    <!--
                    
					<div class="text-center p-t-115">
						<span class="txt1">
							Don’t have an account?
						</span>

						<a class="txt2" href="./register.html">
							Sign Up
						</a>
					</div>
                    -->
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
	
<!--===============================================================================================-->
<script src="{% static 'log/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'log/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'log/vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'log/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'log/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'log/vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'log/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'log/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'log/js/main.js' %}"></script>
</body>
</html>

templates/shop/accounts/forget_password/send_resetpassword_email.html
{% autoescape off %}

Hi {{user.first_name}},

Please click on below link to reset your password.
http://{{domain}}{% url 'accounts:resetpassword_validate' uidb64=uid token=token %}

{% endautoescape %}