accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),

    path('', views.dashboard, name='dashboardd'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    
    path('forget_password/', views.forget_password, name="forget_password"),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('reset_password/', views.reset_password, name="reset_password"),
]

cart/urls.py
from django.urls import path
from . import views 

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    
    
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from django.utils.regex_helper import normalize
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('shop/<slug:category_slug>/', views.shop, name='categries'),
    path('shop/<slug:category_slug>/<slug:product_details_slug>/', views.product_details, name='product_details'),
    path('run_python_code/', views.run_python_code, name='run_python_code'),
    # path('run_python_code/<int:product_id>/', views.run_python_code, name='run_python_code'),
    path('search/', views.search, name='search'),
    path('review/<int:product_id>/', views.review, name='review'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg, Count


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=250, blank=True)
    image = models.ImageField(upload_to='categories', blank=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'categories'

    def get_category_slug_url(self):
        return reverse('shop:categries', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=300, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    discount = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    image = models.ImageField(upload_to='photos/products')
    stock = models.IntegerField()
    new = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)

    date_joined_for_format = models.DateTimeField(auto_now_add=True)
    last_login_for_format = models.DateTimeField(auto_now=True)
    def created(self):
        return self.date_joined_for_format.strftime('%B %d %Y')
    def updated(self):
        return self.last_login_for_format.strftime('%B %d %Y')

    def __str__(self):
        return self.name
    
    def averageRating(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg
    
    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

    def get_prodcut_details_url(self):
        return reverse('shop:product_details', args=[self.category.slug, self.slug])
    
    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-date_joined_for_format',)
    


class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)

variation_category_choices = (
    ('color', 'color'),
    ('size', 'size'),
)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choices)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    # user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, blank=True)
    # subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=700, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def update_at(self):
        return self.updated_at.strftime('%B %d, %Y')

    def hour_update(self):
        return self.updated_at.strftime('%H:%M:%S')

    def __str__(self):
        return self.review


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None ,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_gallery')
    
    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

    def __str__(self):
        return self.product.name

shop/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['review', 'rating']

shop/views.py
from pathlib import Path

from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.conf import settings
from .models import Product, Category
from cart.views import _cart_id
from cart.models import CartItem
from .models import ReviewRating
from .forms import ReviewForm
from django.contrib import messages
from orders.models import OrderProduct
from .models import ProductGallery
from django.shortcuts import render
import cv2
import os
import cvzone
from cvzone.PoseModule import PoseDetector
from django.http import JsonResponse
def home(request):
    products = Product.objects.all().filter(is_available=True)
    
    context = {
        'products' : products,
    }
    return render(request, 'shop/index.html', context)


def shop(request, category_slug=None):
    categories = None
    products = None
    

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        products_count = products.count()
        
    else:
        products = Product.objects.all().filter(is_available=True)
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        products_count = products.count()
        
    
    for product in products:
        reviews = ReviewRating.objects.order_by('-updated_at').filter(product_id=product.id, status=True)

    context = {
        'category_slug': category_slug,
        'products' : paged_products,
        'products_count': products_count,
        
    }
    return render(request, 'shop/shop/shop.html', context)


def product_details(request, category_slug, product_details_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_details_slug)
        
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()
    except Exception as e:
        return e

    if request.user.is_authenticated:
        try:
            orderproduct = OrderProduct.objects.filter(user=request.user, product_id=single_product.id).exists()
        except OrderProduct.DoesNotExist:
            orderproduct = None
    else:
        orderproduct = None

    reviews = ReviewRating.objects.order_by('-updated_at').filter(product_id=single_product.id, status=True)
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)

    context = {
        'single_product': single_product,
        'in_cart': in_cart,
        'orderproduct':orderproduct,
        'reviews': reviews,
        'product_gallery':product_gallery,
    }
    return render(request, 'shop/shop/product_details.html', context)


def search(request):
    products_count = 0
    products = None
    paged_products = None
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword :
            products = Product.objects.filter(Q(description__icontains=keyword) | Q(name__icontains=keyword))
            
            products_count = products.count()
            
    
    context = {
        'products': products,
        'products_count': products_count,
    }
    return render(request, 'shop/shop/search.html', context)



def review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id,product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you, your review updated!')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'Thank you, your review Posted!')
                return redirect(url)


def run_python_code(request):
    product_name = request.GET.get('name','')
    shirt_path = os.path.join(settings.BASE_DIR, f'media/photos/products/{product_name}.png')

    cap = cv2.VideoCapture(0)
    detector = PoseDetector(staticMode=False,
                            modelComplexity=1,
                            smoothLandmarks=False,
                            enableSegmentation=False,
                            smoothSegmentation=True,
                            detectionCon=0.5,
                            trackCon=0.5)

    # Path to the shirt image

    imgshirt = cv2.imread(shirt_path, cv2.IMREAD_UNCHANGED)

    fixedratio = 262 / 190  # width of shirt / width of points
    shirt_ratio_width_height = 581 / 440


    # Define the face landmark indices to ignore
    face_landmark_indices = list(range(0, 17))

    while True:
        success, img = cap.read()

        # Detect pose
        img = detector.findPose(img, draw=False)

        # Find the landmarks, bounding box, and center of the body in the frame
        # Set draw=True to draw the landmarks and bounding box on the image
        lmList, bboxInfo = detector.findPosition(img, draw=False, bboxWithHands=False)

        # Check if any body landmarks are detected
        if lmList:
            lm11 = lmList[11][0:2]
            lm12 = lmList[12][0:2]

            width_of_shirt = int((lm11[0] - lm12[0]) * fixedratio)
            imgshirt_resized = cv2.resize(imgshirt, (width_of_shirt, int(width_of_shirt * shirt_ratio_width_height)))
            currentscale = (lm11[0] - lm12[0]) / 190
            offset = int(44 * currentscale), int(48 * currentscale)

            try:
                img = cvzone.overlayPNG(img, imgshirt_resized, (lm12[0] - offset[0], lm12[1] - offset[1]))
            except:
                pass

        cv2.imshow("Image", img)

        if cv2.waitKey(1) == 27:
            cv2.destroyAllWindows()
            cap.release()
            break
    return render(request, 'index.html')

templates/shop/shop/product_details.html
{% extends '../../base.html' %}
{% load static %}
{% block title %}{{single_product.name}}{% endblock %}
{% block content %}

<div style="background:#40394a" class="pages-title section-padding">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="pages-title-text text-center">
					<h2 style="color:#f4cca4">{{single_product.name}}</h2>
					<ul class="text-left">
						<li><a style="color:#d99879" href="\">Home </a></li>
						<li style="color:#d99879"><span> // </span><a style="color:#d99879"
								href="{% url 'shop:shop' %}">shop </a></li>
						<li style="color:#d99879"><span> // </span>{{single_product.category}}</li>
						<li style="color:#d99879"><span> // </span>{{single_product.name}}</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- pages-title-end -->
<!-- product-details-section-start -->
<div style="background:#1c1427" class="product-details pages section-padding-top">
	<div class="container">
		<div class="row">
			<div style="font-size:18px;">
				{% include "includes/alerts.html" %}
				<div>
					<div class="single-list-view">
						<div class="col-xs-12 col-sm-5 col-md-4">
							<div class="quick-image">
								<div class="single-quick-image text-center">
									<div class="list-img">
										<div class="product-img tab-content">
											<div class="simpleLens-container tab-pane active fade in mainImage">
												<a class="simpleLens-image"
													data-lens-image="{{single_product.image.url}}" href="#"><img
														style="border-radius:10px;" src="{{single_product.image.url}}"
														alt="" class="simpleLens-big-image"></a>
											</div>
										</div>
									</div>
								</div>
								<div class="quick-thumb">
									<ul class="product-slider thumb">
										<li><a href="{{ single_product.image.url }}" data-lens-image="{{single_product.image.url}}" target="mainImage"><img style="width:85px; height:100px; border-radius:10px" src="{{single_product.image.url}}" alt="quick view" /></a></li>
										{% for i in product_gallery %}
										<li><a href="{{i.image.url}}" data-lens-image="{{i.image.url}}" target="mainImage"><img  style="width:85px; height:100px; border-radius:10px" src="{{i.image.url}}" alt="quick view" /></a></li>
										{% endfor %}
									</ul>
								</div>
							</div>
						</div>
						<div class="col-xs-12 col-sm-7 col-md-8">
							<div class="quick-right">
								<div style="border-radius:10px;" class="list-text">
									<h3 style="color:#d99879">{{single_product.name}}</h3>
                  <h5>{% if single_product.discount != 0.00 %}<del>₹{{single_product.discount}}</del>{% endif %}
									<div class="ratting floatright">
										<p style="font-size:1.5rem">( {{single_product.countReview}} Rating )</p>
										<div style="float:right; font-size:1.5rem" class="rating-star">
                      <span>
                        <i class="fa fa-star{% if single_product.averageRating < 0.5 %}-o{% elif single_product.averageRating >= 0.5 and single_product.averageRating < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if single_product.averageRating < 1.5 %}-o{% elif single_product.averageRating >= 1.5 and single_product.averageRating < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if single_product.averageRating < 2.5 %}-o{% elif single_product.averageRating >= 2.5 and single_product.averageRating < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if single_product.averageRating < 3.5 %}-o{% elif single_product.averageRating >= 3.5 and single_product.averageRating < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
                        <i class="fa fa-star{% if single_product.averageRating < 4.5 %}-o{% elif single_product.averageRating >= 4.5 and single_product.averageRating < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
                    
                      </span>
                    </div>
									</div>
                  ₹{{single_product.price}}</h5>
									<p>{{single_product.description}}.</p>

									<form action="{% url 'cart:add_cart' single_product.id %}" method="POST">
										{% csrf_token %}
										<div class="all-choose">
											{% if single_product.variation_set.colors %}
											<div style="margin-right:40px"
												class="col-xs-12 col-sm-7 col-md-5  s-shoose">
												<p style="font-size:20px; margin-bottom:5px">Color</p>
												<select name="color" class="form-control" required>
													<option value="" disabled selected>Select</option>

													{% for x in single_product.variation_set.colors%}
													<option value="{{x.variation_value | lower}}">
														{{x.variation_value | capfirst}}</option>
													{% endfor %}

												</select>
											</div>
											{% endif %}
											{% if single_product.variation_set.sizes %}
											<div class="col-xs-12 col-sm-7 col-md-5 s-shoose ml-3">
												<p style="font-size:20px; margin-bottom:5px">Size</p>
												<select name="size" class="form-control" required>
													<option value="" disabled selected>Select</option>

													{% for x in single_product.variation_set.sizes%}
													<option value="{{x.variation_value | lower}}">
														{{x.variation_value | capfirst}}</option>
													{% endfor %}

												</select>
											</div>
											{% endif %}
											<br><br>
											<br>
											<br>
											<div class="s-shoose">
												<br>
												{% if single_product.stock <= 0 %}
												<div style="font-size:18px" class="alert alert-info text-center"
													role="alert">
													<b>This Product Not In Stock Now, Try Later</b>
												</div>
												{% else %}
												<!--
											{% if in_cart %}
											<br><br>
											<div style="font-size:18px; width:100%" class="container alert alert-success text-center" role="alert">
											<b>This Product Already in Cart,&nbsp;&nbsp; <a href="{% url 'cart:cart' %}" style="color:#064420;text-decoration: underline;">Go To Cart<a></b>
											</div>
											{% else %}
											<div class="list-btn floatright">
												<button type="submit" class="btn btn-warning" style="background:#eb5e0b; font-size:18px">Add to cart <i class="mdi mdi-cart-outline"></i></button>
											</div>
											{% endif %}
											-->
												<div class="list-btn floatright">
													<button type="submit" class="btn "
														style="background:#f4cca4;color:#1c1427; font-size:18px"><b>Add
															to cart <i class="mdi mdi-cart-outline"></i></b></button>
												</div>
			<div class="list-btn floatright">
    <a href="#" onclick="runPythonCode()" class="btn " style="background:#f4cca4;color:#1c1427; font-size:18px">Try on</a>
</div>

												{% endif %}
												<br>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- single-product item end -->
				<!-- reviews area start -->
				<div class="row">
					<div class="col-xs-12">
						<div style="border-radius:10px;" class="reviews padding60 margin-top">
							<ul class="reviews-tab clearfix">

								<li class="active"><a style="font-size:25px;color:#d99879" data-toggle="tab"
										href="#reviews">Rate and review</a></li>

							</ul>
							<div class="tab-content">

								<div class="info-reviews review-text tab-pane fade in active" id="reviews">
									<div>
										<form action="{% url 'shop:review' single_product.id %}" method="POST">
											{% csrf_token %}
											<div class="your-rating log-title">

												<h5>Product rating</h5>
												<!-- Stars Review -->
												<div class="rate">
													<input type="radio" name="rating" id="rating10" value="5"
														required /><label for="rating10" title="5"></label>
													<input type="radio" name="rating" id="rating9" value="4.5"
														required /><label for="rating9" title="4.5"
														class="half"></label>
													<input type="radio" name="rating" id="rating8" value="4"
														required /><label for="rating8" title="4"></label>
													<input type="radio" name="rating" id="rating7" value="3.5"
														required /><label for="rating7" title="3.5"
														class="half"></label>
													<input type="radio" name="rating" id="rating6" value="3"
														required /><label for="rating6" title="3"></label>
													<input type="radio" name="rating" id="rating5" value="2.5"
														required /><label for="rating5" title="2.5"
														class="half"></label>
													<input type="radio" name="rating" id="rating4" value="2"
														required /><label for="rating4" title="2"></label>
													<input type="radio" name="rating" id="rating3" value="1.5"
														required /><label for="rating3" title="1.5"
														class="half"></label>
													<input type="radio" name="rating" id="rating2" value="1"
														required /><label for="rating2" title="1"></label>
													<input type="radio" name="rating" id="rating1" value="0.5"
														required /><label for="rating1" title="0.5"
														class="half"></label>
												</div>
											</div>
											<br>
											<div class="custom-input">
												<div class="row">
													<div class="col-xs-12">
														<div class="custom-mess">
															<textarea style="border:2px solid #F4CCA4"
																class="form-control" name="review"
																placeholder="Review..." rows="2"></textarea>
														</div>
													</div>
													<div class="col-xs-12"><br>
														<div class="submit-text">
															{% if user.is_authenticated %}


															{% if orderproduct %}
															<!--<input style="width:20%;float:right;margin-button:20px" type="submit" value="Post Review" class="btn btn-warning">-->
															<button type="submit" class="btn btn-warning"
																style="background:#f4cca4;color:#1c1427; font-size:18px;float: right;"><b>submit
																	review </b></button>
															{% else %}
															<div style="font-size:18px;margin-top:10px;width: 75%;"
																class="container alert alert-info text-center"
																role="alert">
																You must buy this product to review on it!
															</div>
															{% endif %}

															{% else %}
															<div style="font-size:18px;margin-top:10px;width: 75%;"
																class="container alert alert-info text-center"
																role="alert">
																You must login to rate and review,<a
																	style="background:none; color:#000; margin-left: -25px;"
																	href="{% url 'accounts:login' %}">Login</a>
															</div>
															{% endif %}

														</div>
													</div>
												</div>
											</div>
										</form>
									</div>
									<br>
									<br>
									<hr>
									<div class="about-author">
										<h3 class="text-center" style="color:#D99879">Customer rating</h3><br>
										{% if reviews %}
										{% for review in reviews %}
										<div style="background:#1C1427; padding:20px; border-radius:15px" class="autohr-text ">
											<img style="width:50px; height:50px; border-radius:50%" src="{{review.user.userprofile.profile_picture.url}}" class="img-xs icon rounded-circle">
											
											<div class="author-des">
												<span
													style="color:#F4CCA4; float:right; font-size:14px">{{review.update_at}}</span>
												<h4 style="color:#d99879">{{review.user.full_name}}</h4>


												<div class="rating-star">
													<span>
														<i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}"
															aria-hidden="true"></i>
														<i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}"
															aria-hidden="true"></i>
														<i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}"
															aria-hidden="true"></i>
														<i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}"
															aria-hidden="true"></i>
														<i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}"
															aria-hidden="true"></i>
													</span>
												</div><br>

												<p style="font-size:18px;margin-top:15px">{{review.review}}</p>
											</div>
										</div>
										<hr />
										{% endfor %}
										{% else %}
										<br>
										<div style="font-size:16px" class="alert alert-info text-center" role="alert">
											Be First Reviewer!
										</div>
										{% endif %}
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<br>
  </div>
</div>

<script>
		function runPythonCode() {
		var productName="{{single_product.name}}";
		var url = `/run_python_code?name=${productName}`;
    fetch(url)
        .then(response => {
            if (response.ok) {
                console.log('Python code executed successfully.');
                // You may want to perform additional actions upon successful execution
            } else {
                console.error('Failed to execute Python code.');
                // You may want to handle this error case appropriately
            }
        })
        .catch(error => {
            console.error('Error:', error);
            // You may want to handle this error case appropriately
        });
}
</script>

{% endblock %}